### ISSUE TITLE
Semantic issue?

### ISSUE THREAD

**Issue by barrylachapelle** [sortofsleepy/arkit-tests#2]
Hi. Getting some semantic issue error on build. Any thoughts?

<img width="1462" alt="screen shot 2017-08-11 at 12 38 05" src="https://user-images.githubusercontent.com/1087169/29200650-fa1872b8-7e91-11e7-8f6d-b5fea8790efd.png">

**Comment by sortofsleepy** [comment]
Hi @barrylachapelle !

hmmm that's not something I've seen yet(or tried using yet). It looks like it ought to build fine based on the docs 😕 . I assume you're messing around with Zach's example project? 

I'm not at my work computer just yet but did you happen to try `matrix_float4x4` instead of `simd::float4x4`? I assume there's really no difference but maybe using SIMD needs the addition of another framework, `matrix_float4x4` should be bundled in the ARKit framework. 

I'll try to take a look later today or sometime over the weekend more in depth if I have time

**Comment by sortofsleepy** [comment]
Ok! had some time. I believe the issue is that the API has changed, though to be honest I'm not sure how since I haven't really updated xcode¯\_(ツ)_/¯ and I'm not sure if you're exactly experiencing the same thing.

So for whatever reason, I didn't get a build error when trying to acquire the view matrix, but I did on the projection matrix. I had to change that line to 

```objective-c
// turns out matrix_float4x4 is an alias for the SIMD stuff.

 matrix_float4x4 projectionMatrix = [session.currentFrame.camera projectionMatrixWithViewportSize:_viewportSize orientation:UIInterfaceOrientationPortrait zNear:0.01 zFar:1000.0];
            

```

Maybe you need to update xcode? I'm not sure why you're erroring out on the view matrix call as well.

**Comment by barrylachapelle** [comment]
Yes! @sortofsleepy upgrading to beta 5 worked perfectly. Thanks for putting this together.

**Comment by sortofsleepy** [comment]
🎉 🎉 no problem! (but in all seriousness I haven't actually done all that much haha)
