### ISSUE TITLE
iPad Pro - drawPointCloud() draws grey screen.

### ISSUE THREAD

**Issue by pointshader** [sortofsleepy/arkit-tests#21]
Develop branch, commit 922a2a4

In example-basic, replacing 
`perform->draw()`
with
`perform->drawPointCloud()`
produces a grey texture. Overlaying AR objects on top still works. 

I tried directly calling 
` processor->pointCloud.setup();` in the main setup function and
`processor->pointCloud.updatePointCloud(session.currentFrame);` in the update function just to ensure the point cloud setup & update functions were being hit, but that didn't seem to affect anything.

Should I be expecting a different output from this function? Does drawPointCloud() need to be put after a camera matrix transform that I'm missing? Thanks in advance.

**Comment by sortofsleepy** [comment]
hey @64BitsPerMinute !

hmmm that does sound unusual. Could you be more specific? You should be seeing relatively tiny colored squares pop up whenever ARKit detects features. 

By chance, have you also tried including `ARDebugUtils` directly and building a new instance of the `PointCloudDebug` class? Does it produce the same result?

When you have a moment, a screenshot would also be helpful so I can confirm and understand what it is you're seeing.

**Comment by pointshader** [comment]
I went to pack up the iPad later that afternoon, and as I lifted it up I finally did see the yellow squares as expected ( they definitely weren't appearing before ). So either A) I didn't 'scan' my room completely enough for the debug information to show initially in the several tries of getting it to work B) There's a time based bug or C) Neither of the above. 

I'll try to collect more data today or tomorrow, this could potentially just be user error.

**Comment by sortofsleepy** [comment]
@64BitsPerMinute Yea, for feature detection, the software needs a bit of variation in the image in order to pick up on anything, that could have been it as well. 

Anyways, I'm gonna close this since it sounds like things are working and I haven't heard otherwise from you yet. If the issue persists, feel free to re-open and I can take a look again but I'm not sure how much I can do since I'm just picking up the points from the framework and piping them to the screen.
