### ISSUE TITLE
Tracking State

### ISSUE THREAD

**Issue by aferriss** [sortofsleepy/arkit-tests#22]
I haven't looked into this much yet, but it could be nice to provide a wrapper around the [ARCamera tracking state.](https://developer.apple.com/documentation/arkit/arcamera/2880259-trackingstate?language=objc)

Something like `getTrackingState()` might suffice. ARKit also provides [reasons](https://developer.apple.com/documentation/arkit/artrackingstatereason?language=objc) why tracking might be inhibited, which could be useful for debugging or providing user feedback.

**Comment by sortofsleepy** [comment]
Oh finally! Nice find on that, didn't notice that was added, will be nice to finally understand why I sometimes see a tracking error. I'll look to add that maybe sometime tomorrow.

**Comment by sortofsleepy** [comment]
ok! added - you should be able to pull the tracking state with `getTrackingState` on both `ARCam` and `ARProcessor`. Also added a logging function called `logTrackingState`. 

I kinda made up the strings in the logging function but hopefully should be clear. 

You'll only be able to get a message for `logTrackingState` if you turn on debug mode which I decided ought to actually be turned off by default instead of on by default like it is now. You can turn it on by passing `true` to either of those classes setup functions to turn it on right away or call `toggleDebugMode`

**Comment by aferriss** [comment]
Awesome, thanks! I'll give it a whirl :D

**Comment by sortofsleepy** [comment]
@aferriss  - gonna close this now since I'm guessing things are working? Feel free to re-open if not.
