### ISSUE TITLE
ipad camera zoom/cropping

### ISSUE THREAD

**Issue by sortofsleepy** [sortofsleepy/arkit-tests#23]
(starting a new issue due to it being mentioned in a somewhat un-related issue. )
@HKBMedialab
Have you compared the zoomed in image to a blank ARProject? [The reason there is a zoom is early users reported a odd distortion effect happening on the camera image](https://github.com/sortofsleepy/ofxARKit/issues/4)

(note - I don't have an Ipad or access to one but I'll do my best here)

**Comment by HKBMedialab** [comment]
i just set up a new Metal ARProject in Xcode. Its a very significant difference:
Metal ARProject:
![img_0067](https://user-images.githubusercontent.com/17779154/30664432-0056a42a-9e4e-11e7-8df2-894b3be6cc71.jpg)
ofxARKit:
![img_0068](https://user-images.githubusercontent.com/17779154/30664433-00697960-9e4e-11e7-923c-fee8dc299eb4.PNG)

**Comment by sortofsleepy** [comment]
ah drat 😢  Was hoping that would work. 

hmmm, maybe we'll get lucky and it'll be an easy fix now that things seem to be normalized between ipads and iphones. 

In `ARCam.mm`, what happens when you comment out line 57 which should have `needsPerspectiveAdjustment = true;` ? on it

**Comment by HKBMedialab** [comment]
hey @sortofsleepy 
if I comment out line 57, then the zoom is about right. but there is a wrong/weird aspect ratio going on. sort of like mentioned in issue #4. Weird here is, that if i have the iPad locked to Portrait, things get distorted in width, if i then turn my device to landscape without a orientationChange event (still locked iPad), things get distorted in their height. that makes sense if things get streched in x direction in respect to a portrait screen.

![img_0081](https://user-images.githubusercontent.com/17779154/30719731-f008442a-9f24-11e7-9c33-e226d747e995.PNG)

![img_0082](https://user-images.githubusercontent.com/17779154/30719766-14052a8c-9f25-11e7-8e90-bfa842add4d4.PNG)

**Comment by sortofsleepy** [comment]
Ah drat .. not my day today haha. 

Ok ! I'm gonna close this issue and re-open the other then, please follow along there.

**Comment by HKBMedialab** [comment]
@sortofsleepy thanks for all your good work! It makes sense, to close this one and reopen the old one as i found out, my rotation problem in the first place is bound to the zoomLevel which both are about how to deal screenratio: 
My camfeed was flipped and zoomed in because of in ARUtils.h in Line 106
`getNativeAspectRatio()` returned 0.75 instead of 1.333. So that was why the image was flipped. 
In Line 108 it has to be `return screenSize.y / screenSize.x;` (longer side/shorter side) instead of `return screenSize.x / screenSize.y;` to get the 1.333. The bad news is though, that this also means, that my iPad should aparantly rotate different again than your iPhone. So then we have to revert back the -90 rotation changes. Not sure why iPad and iPhone do not the same thing here as nativeBounds should be in respect of Portrait Up on all devices, as far as I understand this: 
https://developer.apple.com/documentation/uikit/uiscreen/1617810-nativebounds
I will leave this for now and switch to your new camera-correction branch. Thanks again for that! 
I am happy to help with this issue, but i am not sure if my skills keep up with that...

**Comment by sortofsleepy** [comment]
@HKBMedialab 
Thanks for investigating! I hardcoded a zoom level for the time being in the `camera-correction` branch but thanks to your information, it gives me a good starting point to try and figure out a better way of coming up with that value. In respect to rotation, I think though you were more on the ball with that, as far as I can  tell, rotation is fine.

Your understanding of what `nativeBounds` is supposed to do was basically my understanding of it as well, I think we both got tripped up(and this is really my fault) on how orientation events are handled. 

If the device is locked to an orientation, it will always return that orientation no matter what the actual physical orientation of the device is.  I had for some reason got it in my head that one of the Objective-C calls I was trying ignored that lock. ~~Even if the call were not always in respect to portrait up, since the device is locked it will always return `return screenSize.x / screenSize.y;`.~~(see edit)When the device is locked, there isn't a way to get the orientation without turning to Accelerometer events. 

So all in all, you should just ignore the stupid advice I spouted back in #19 about having less trouble locking the device,  I clearly wasn't thinking that day haha.

And as far as help, no worries! Even testing helps me cause I won't always have access to that iPad. 

(side note - also next time, just reply in issue #4 , makes it easier to keep track of the conversation)

__Edit__
To clarify how `getNativeAspectRatio` works - `getNativeDeviceDimensions` accounts for that orientation flip, the issue is with the device locked, it thinks it's in portrait, hence, it will return the wrong value.

**Comment by sortofsleepy** [comment]
Since this issue appears to be getting some views for some reason - note that today, the new Metal based camera renderer was pushed into `master`. Give it a whirl! It fixes a lot of the issues in this issue.
