### ISSUE TITLE
"No such file" error in build

### ISSUE THREAD

**Issue by joshkpeterson** [sortofsleepy/arkit-tests#25]
I'm very new to oF, apologies if this is a basic config issue and thanks for your help.

On a fresh install of of_v0.9.8_ios_release, iphone 7+, iOS11

When I build example-basic, I get the following error:

```
clang: error: no such file or directory: '/Users/joshy/projects/of_v0.9.8_ios_release/apps/myApps/src/ARAnchorManager.mm'
clang: error: no input files
```

It's looking for this file one level up from the project. The project path is:
/Users/joshy/projects/of_v0.9.8_ios_release/apps/myApps/example-basic

The addon is at:
/Users/joshy/projects/of_v0.9.8_ios_release/addons/ofxARKit

Thank you!

**Comment by sortofsleepy** [comment]
Hey @joshkpeterson ! No worries about basic questions, we all start out as beginners at some point in our lives! I did make some assumptions when writing up the readme so it's possible I might not have been as clear as I could have been. 

How did you generate the project at `/Users/joshy/projects/of_v0.9.8_ios_release/apps/myApps/example-basic`
?
It sounds like you copied the example project into the `myApps` folder, which technically is fine but it means you'll have to manually change the paths in `Project.xcconfig`

There should be a project generator application in the openFrameworks folder, that's where you ought to start from when you start a new project. [Here's a link describing it](http://openframeworks.cc/learning/01_basics/create_a_new_project/)

**Comment by joshkpeterson** [comment]
Ah okay, was able to run one of the examples now. Thanks!

**Comment by ofZach** [comment]
one thing I've noticed with some of the xcode betas is that sometimes I have to be more explicit about the files target membership -- that it can be unclicked even if I select it on drag & drop and I need to select it again through this sidebar. 

<img width="267" alt="screen shot 2017-09-21 at 11 38 50 pm" src="https://user-images.githubusercontent.com/142897/30728424-180f13d0-9f26-11e7-8698-173c4318ed43.png">

I don't think that's your problem here exactly but it is something I've seen where files don't get compiled and you get linking errors.

**Comment by joshkpeterson** [comment]
Thanks @ofZach that's good to keep in mind!
