### ISSUE TITLE
get world point in screen coords

### ISSUE THREAD

**Issue by aferriss** [sortofsleepy/arkit-tests#27]
One useful function I've been using a bunch seems missing from the library, wonder if you'd consider adding something like this in.  I know it's pretty standard code, but I found it useful. 

I know there is also a worldToScreen in ofCamera, I haven't tried it out, but maybe that would suffice?

```
ofVec2f worldToScreen(ofPoint worldPoint){
    ARCommon::ARCameraMatrices mats = processor->getCameraMatrices();
    
    ofVec4f p =  ofVec4f(worldPoint.x, worldPoint.y, worldPoint.z, 1.0);
    
    p = p * mats.cameraView;
    p = p * mats.cameraProjection;
    
    p /= p.w;
    
    // convert coords to 0 - 1
    p.x = p.x * 0.5 + 0.5;
    p.y = p.y * 0.5 + 0.5;

    // convert coords to pixels
    p.x *= ofGetWidth();
    p.y *= ofGetHeight();
    return ofVec2f(p.x, p.y);
}
```

**Comment by sortofsleepy** [comment]
I hadn't actually considered the need to convert from world coordinates, 😓 . But yea this definitely sounds like it makes sense to add.  

I can add that this weekend. I don't think I'll have a moment to make a test case, but offhand, looking at ofCamera, the built-in function seems like it relies on having set the global projection and view matrices; that being said I think it makes more sense to drop in your code which is what I'll likely do.

**Comment by aferriss** [comment]
Fwiw the uses I've found for this have been things like, tap to remove a 3d object somewhere in the world so you could say

For ( pt in pts) {
if ( dist(touch, worldToScreen(pt)) { remove pt}
}

Or another use case is when I want to use the camera color to set the color of some 3d thing in the world.

**Comment by aferriss** [comment]
Also similar but slightly unrelated question, ARKit has the hit test result for calculating if a touch hits an in world object, but this relies on scene kit. Wondering if you have thoughts on other ways to do this than what I outlined above?

**Comment by sortofsleepy** [comment]
There is actually a way to use that API call without SceneKit, but I had set that aside for the time being since(thank you for reminding me that it was there though!) I wasn't sure how useful it'd be in a more generalized context as it seems to only work on objects that were added as planes or a detected feature. At least that's the impression I'm getting after reading up again [here](https://developer.apple.com/documentation/arkit/arhittestresult.resulttype) 

Other than your code + hit test, besides coming up with some kind of frankenstein combo of the 2, I don't have have any other bright ideas at the moment of how this could be done better.

**Comment by ofZach** [comment]
not sure if it's helpful but https://github.com/elliotwoods/ofxGrabCam by @elliotwoods  uses some interesting  approaches to selecting
https://www.youtube.com/watch?v=nQUhZzcBLjg

**Comment by sortofsleepy** [comment]
Thanks Zach! I'll take a look and keep that in mind

**Comment by sortofsleepy** [comment]
Ok! I've added that worldToScreen function as a general utility function. Everything has been merged to master. I made a slight tweak, opting to accept a projection and view matrix separately, so it can be used with any camera setup, but otherwise it's the same code.  

I looked at ofxGrabCam and the process Elliot is using appears to be trying to solve the opposite situation, going from screen coordinates and converting to world coordinates. I did only have a moment to look at it briefly, but that was the impression I got from reading the code and trying out the addon. I don't have any doubt's that it could have been adapted to convert world->screen but it seemed like it was going to be more trouble than it's worth. 

That being said though, it is still gonna be useful! I had done a rough first pass at converting from screen coordinates to world a while ago and had something ALMOST working but I was still off a little bit, I think adapting ofxGrabCam will be helpful in that regard. Something I'll sadly need to save till next weekend. 

closing for now.

**Comment by ofZach** [comment]
sorry to clarify my comment about elliot's grabcam addon was in regards to this question: 

`Also similar but slightly unrelated question, ARKit has the hit test result for calculating if a touch hits an in world object, but this relies on scene kit. Wondering if you have thoughts on other ways to do this than what I outlined above?`

not in relation to world to screen conversion....

**Comment by sortofsleepy** [comment]
ah! no worries! Still useful to know about.

**Comment by elliotwoods** [comment]
notes:
* ofCamera has worldToScreen, etc
* ofxGrabCam has screenToWorld using a depth buffer lookup
* If you want to see which object is under the cursor, you could use the ofxGrabCam method to get world position and compare

Correct alternatives to find object under cursor:
1. Create a 'pick ray' and intersect it with every mesh using the CPU (this is the three.js approach)
2. Create an 'object index buffer':
    * second render pass for your scene
    * every object has a shader applied which renders a single unique color value for each object
    * read back the pixel values in that object index buffer to find object under cursor
    * ..
    * this is my preferred approach to finding object under cursor, check ofxGrabScene for experiments with this. I have a video example somewhere but can't find now. Note : GL implementation in openFrameworks was bad at the time for dealing with non-standard fbo formats (e.g. GL_R16 would be erratic and even hard-crashed some macs, so had to use RGA32F every time). I'd recommend to use OpenGL 3 or 4 for your project if you go down this pagh
    * Using this method you can do other useful things too, e.g. drawing an outline around an object (e.g. the one your eye is hovering over)

**Comment by sortofsleepy** [comment]
Thanks for the notes @elliotwoods!
