### ISSUE TITLE
iphone x face tracking related changes

### ISSUE THREAD

**Issue by ofZach** [sortofsleepy/arkit-tests#32]
I will make a PR, just a record of things I'm noticing that need to be fixed: 

a) this: 

` std::vector<FaceAnchorObject> faces;  
`
needs to be public or we need an accessor

b) when we've already found a face, we still need to store the raw pointer: 

```
 if(it != faces.end()){
                    
                    faces[index].raw = pa;

```

c) raw is actually an anchor (extends anchor) which contains a transform, so we can use it 

```
 for (auto & face : processor->anchorController->faces){

            ofMatrix4x4 temp = ARCommon::toMat4(face.raw.transform);
            
            ofPushMatrix();
            ofMultMatrix(temp);
            for (auto & pt : face.vertices){
                 ofCircle(pt, 0.001);
            }
            ofPopMatrix();
        
    }

```

then we're in business: 

<img width="267" alt="screen shot 2018-01-21 at 12 06 10 pm" src="https://user-images.githubusercontent.com/142897/35196682-7bec62b8-fea3-11e7-8ed0-a394d0a85f7f.png">

d) face.mesh seems empty at the moment -- I guess it needs to be constructed.  vertices seem good

**Comment by sortofsleepy** [comment]
🎉 👍 Nice! Thanks for taking the code for a spin and testing things out! 

Changes sound fine to me - minor point on making the faces vector public(good catch too! I totally missed that); I think it might be better to add a getter function instead of just making the vector public? Just so it's clear what `faces` is referring to. 

Also, while I'm happy to look over a PR - you should have push access too; you're more than welcome to just push directly if nothing breaks. Way I've been working is all current changes go into `develop` - that gets merged into `master` , there are some generalized notes in the wiki.

**Comment by sortofsleepy** [comment]
cleaning things up and closing this as it sounds like most if not all of the changes discussed here have made it in via commit 4f07e68 

feel free to re-open if need be
