### ISSUE TITLE
Examples aren't functional out-of-the-box

### ISSUE THREAD

**Issue by aceslowman** [sortofsleepy/arkit-tests#45]
Currently, when either example-planes or example-lighting are built, the only things visible are the debug text and the camera input, with any geometry drawing *beneath* the `processor->draw`. 

It seems to me that there is some kind of depth issue, preventing objects from drawing on top of the camera input.

Is this something that any of you are noticing, or could it in some way come down to my configuration? I'm new to iOS and ARKit, but not new to oF in general.

**Comment by sortofsleepy** [comment]
Hey @aceslowman ! 

This is eh .. news to me. Last I looked, both those examples ought to be working, 
What's your phone model + OS version? 

Do any of the other examples exhibit the same behavior? 

Also, could you by chance provide a screenshot?

**Comment by aceslowman** [comment]
Of course while responding to this, I managed to get planes to draw... 

The lighting example is having the depth issue though, where the camera is only drawing, and the sphere seems to be beneath the camera input.

Last night I updated everything. Previously I was running 11.0 on a iPhone 6s+, which I have now at 11.3. I also updated to the most recent xcode release.

On example-planes, I am still getting:

```
2018-04-12 11:42:17.346326-0600 example-planes[639:41158] [Sensor] ARImageSensor (<ARImageSensor: 0x1c40c70e0>) failed to start!
2018-04-12 11:42:17.349485-0600 example-planes[639:41158] [Session] Session (0x105217a10): did fail with error: Error Domain=com.apple.arkit.error Code=102 "Required sensor failed." UserInfo={NSLocalizedRecoverySuggestion=Make sure that the application has the required privacy settings., NSLocalizedDescription=Required sensor failed., NSLocalizedFailureReason=A sensor failed to deliver the required input.}
```

**Comment by sortofsleepy** [comment]
For the lighting example could you provide a screenshot? I'm not sure what you mean when you say the sphere seems to be beneath the camera input. 

In that example FYI, the sphere isn't positioned with an anchor, it's just a static sphere; so it should be moving with you as you move the phone. 

As to your other issue - I'm not 100% certain as I'm not sure how it could have happened in the first place, but it looks like the privacy settings got borked. In `ofxiOS-Info.plist` check to see if

`Privacy - Camera Usage Description. `

exists and if it doesn't, add it. The value is just whatever you want the user to see when the camera permission request pops up.

**Comment by aceslowman** [comment]
![2018-04-12 12 16 38](https://user-images.githubusercontent.com/6826702/38696108-6ca8d9f2-3e4b-11e8-923a-175f4a16f55e.png)

Here is a screenshot of the lighting example in use. The sphere briefly flashes, before the camera appears. Removing `processor->draw();` allows me to see the sphere on the basic gray background.

As far as the privacy settings go, I've made sure that the Camera Usage Description is set:

![screenshot 2018-04-12 12 20 59](https://user-images.githubusercontent.com/6826702/38696322-10c12b70-3e4c-11e8-9279-f60e8846074b.png)

**Comment by sortofsleepy** [comment]
hmmmm.. interesting - I had a 6s as well when I was building the lighting example and it was working I swear! 😓 As far as I'm aware, it hasn't been touched since then so this is very strange. 

I am unfortunately not in the best position to test anything at the moment as I can't get my hands on a fully functional Mac. 

Just spitballing here with other ideas, have you tried shifting the camera drawing around to draw after the sphere? Have you tried `ofDisableDepthTest();` before `processor->draw`?

As far as the other issue - after googling a bit it helped jog my memory a bit as someone else I believe also encountered this but it's possible it might be a compass issue, see here
https://forums.developer.apple.com/thread/94273

Apologies I can't be of more help at the moment 🙇, happy to keep suggesting other stuff to try; maybe one of the other contributors will be able to help test.

**Comment by sortofsleepy** [comment]
This looks potentially be helpful with the weird unrelated privacy error message
https://stackoverflow.com/questions/49058263/arkit-setting-worldtrackingconfiguration-to-gravityandheading-produces-error?noredirect=1&lq=1

**Comment by aferriss** [comment]
There's also this thread which also points to a compass issue. I'd try the compass calibration and setting your worldAlignment to gravity. 

https://stackoverflow.com/questions/45655562/apple-ios-arkit-a-sensor-failed-to-deliver-the-required-input-error-and-stops?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by sortofsleepy** [comment]
Ok! Since there hasn't been much activity I'm going to assume you figured out a way around things Austin and close this to keep things neat. 

Just in case you haven't though, it finally occurred to my why the lighting example might be failing. Now I've only tested this on a desktop, but if you disable depth testing in the example, you ought to be able to see the sphere. 

I made a test case (there are some things slightly different but it should basically render the same things as the example): 
https://gist.github.com/sortofsleepy/0559865c407e641c64034bcc8e08985e

One thing that hadn't occurred to me was that I had changed the default drawing format of the camera. It used to simply render a texture, but at some point with some change to iOS, that was causing an occasional dip in FPS. So I changed things to render a straight VBO mesh to try and solve that; things were also changed to try to figure out a more universal way of dealing to cropping and scaling issues of the camera due to some folks with iPads noticing things were off. 

Hope that helps! If not, feel free to re-open and we can continue to troubleshoot.
