### ISSUE TITLE
Looks like something is missing from the default examples as a result of AirPods integration.

### ISSUE THREAD

**Issue by garrettburnett** [sortofsleepy/arkit-tests#80]
The only example that works out of the box is the AirPods example. It seems like there's a missing framework that needs to be added.

The following errors display on other Xcode projects:
- Undefined symbol: _OBJC_CLASS_$ARAirPodMoves
- Undefined symbol: _OBJC_CLASS_$AttitudeOFBridge

**Comment by sortofsleepy** [comment]
Hey there! Thanks for catching that. Since I don't have a whole lot of time to consistently work on this, especially since I use Windows for pretty much everything these days, the general policy for me on this has been to put faith into the people behind the PRs, looks like they messed up. 

If you could confirm(don't have a Mac setup with Xcode at the moment, will take some time) , if you look at `ARProcessor.h` and `ARProcessor.mm`, and comment out all the airpods related stuff, do things build then?

**Comment by ofZach** [comment]
can confirm removing all AirPods related code gets rid of the undefined symbols....

**Comment by ofZach** [comment]
looking at it may not be a missing framework, but that ARAirPodMoves.h / .mm is missing from the example projects...

**Comment by sortofsleepy** [comment]
> don't have a Mac setup with Xcode at the moment, will take some time

Lol - ok small update looks like I need to update OS X as well ha. 

> can confirm removing all AirPods related code gets rid of the undefined symbols....

Thanks for looking Zach!  Hmm ok I guess I'll throw em behind ifdefs, seems like the best way forward at the moment.

**Comment by ofZach** [comment]
I think *need to double check* that just regenerating the project files will fix this -- it's mostly like the examples are missing the ARAirPodMoves.h and .mm file -- thus the missing symbols.  prob an ifDef will help too

**Comment by sortofsleepy** [comment]
After thinking about it a bit more I think the right move is to just take the Airpods stuff out of the processor class, it doesn't really make sense to me to have it there since it's not technically a part of ARKit. My bad on not being more on top of this, many apologies!

Big Sur and XCode are FINALLY downloaded, I've made some initial changes and I'll find some time to test and push a fix later this week.

**Comment by garrettburnett** [comment]
> Big Sur and XCode are FINALLY downloaded, I've made some initial changes and I'll find some time to test and push a fix later this week.

Appreciated! Just had to download the same things myself recently and it definitely takes forever!

**Comment by sortofsleepy** [comment]
> > Big Sur and XCode are FINALLY downloaded, I've made some initial changes and I'll find some time to test and push a fix later this week.
> 
> Appreciated! Just had to download the same things myself recently and it definitely takes forever!

Of course! 

It's gonna be a little while longer though unfortunately, if you want to move forward with your project, I would just go ahead and delete all the Airpods related stuff and keep moving.  

Speaking of which, you may run into this issue as well - I spent a little bit of my free time today to prepare to push changes and crashed into Big Sur . For some reason adding the necessary frameworks in the add-on causes incorrect values to be generated somewhere resulting in just a complete cluster-f when you try to go build including weirdly enough OpenGL related errors 😢 . 

To fix an existing project, look at the project file's build settings and under "Framework Search Paths", delete all the absolute paths(you may have to re-add the frameworks also)

So I need to find the time to either figure out how to get the right paths to generate or just re-add all the necessary frameworks to the examples. I will look into doing that this weekend. 

The additional frameworks you'll have to add include 
* ARKit
* Metal
* MetalKit

Apologies again!

**Comment by sortofsleepy** [comment]
Ok! So I ended up just throwing my hands in the air and tweaking the paths of each example project. It might be an issue with just my install it seems so I may go back and re-install everything to see if it fixes it but for now I think this is fine. 

Things should be fixed now and the examples should work so I will close this issue - if something is wrong or missing, please let me know.
